name: "Security Scanning"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  scan:
    name: Security Scan
    uses: chrisns/.github/.github/workflows/security-scan.yml@eabb970df666c345d1bf55be1c53e49165f49ef9 # main
    permissions:
      security-events: write
      statuses: write
      contents: read
      actions: read
