name: "Security Scanning"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  scan:
    name: Security Scan
    uses: chrisns/.github/.github/workflows/security-scan.yml@3a0d8ca8f3c71d027aec784fbb2d4478eee2a238 # main
    permissions:
      security-events: write
      statuses: write
      contents: read
      actions: read
