name: "Security Scanning"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  scan:
    name: Security Scan
    uses: chrisns/.github/.github/workflows/security-scan.yml@e71da12d258ef618c89d5a9a9639b480297937a3 # main
    permissions:
      security-events: write
      statuses: write
      contents: read
      actions: read
